export const REQUEST_RESULTS = 'REQUEST_RESULTS';
export const REQUEST_RESULTS_SUCCESS = 'REQUEST_RESULTS_SUCCESS';
export const REQUEST_RESULTS_FAILURE = 'REQUEST_RESULTS_FAILURE';
export const RESET_CURRENT_QUERY = 'RESET_CURRENT_QUERY';

export const REQUEST_MORE_RESULTS = 'REQUEST_MORE_RESULTS';
export const REQUEST_MORE_RESULTS_SUCCESS = 'REQUEST_MORE_RESULTS_SUCCESS';
export const REQUEST_MORE_RESULTS_FAILURE = 'REQUEST_MORE_RESULTS_FAILURE';
